# -*- coding: utf-8 -*-
"""credit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16cOWKZwQN-KSGjhFi9ZUV79qZUDLNQ8O
"""

from google.colab import files
uploaded=files.upload()

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error

import plotly.express as px

df = pd.read_csv("credit_card_fraud_synthetic.csv")

print("\nDataset Shape:", df.shape)
print(df.head())

print("\nMissing Values:\n", df.isnull().sum())

df = df.drop_duplicates()

print("\nAfter removing duplicates:", df.shape)

print("\nDescription:\n", df.describe())

print("\nClass Count:\n", df['Class'].value_counts())

sns.countplot(x='Class', data=df)
plt.title("Fraud vs Normal Transactions")
plt.show()

sns.histplot(df['Amount'], bins=50, kde=True)
plt.title("Transaction Amount Distribution")
plt.show()

plt.figure(figsize=(8,5))
sns.boxplot(x='Class', y='Amount', data=df)
plt.title("Fraud vs Normal Amount")
plt.show()

plt.figure(figsize=(12,8))
sns.heatmap(df.corr(), cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

def risk_level(amount):
    if amount < 50:
        return "Low Risk"
    elif amount < 200:
        return "Medium Risk"
    else:
        return "High Risk"

df['Risk'] = df['Amount'].apply(risk_level)

print(df[['Amount','Risk']].head())

X = df[['Time', 'Amount']]
y = df['Class']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("\nR2 Score:", r2_score(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))

fraud = df[df['Class'] == 1].shape[0]
normal = df[df['Class'] == 0].shape[0]

print("\nFraud Transactions:", fraud)
print("Normal Transactions:", normal)
print("Fraud Percentage:", fraud / len(df) * 100)

import plotly.io as pio
pio.renderers.default = "colab"

fig1 = px.histogram(df, x='Class', color='Class',
                    title="Fraud vs Normal Transactions")
fig1.show()

fig2 = px.scatter(df, x='Time', y='Amount', color='Class',
                  title="Time vs Transaction Amount")
fig2.show()

fig3 = px.histogram(df, x='Risk', color='Risk',
                    title="Transaction Risk Levels")
fig3.show()

fig4 = px.imshow(df.drop(columns=['Risk']).corr(),
                 title="Correlation Heatmap")
fig4.show()

print("\nProject Completed Successfully 🚀")